# Generated by Django 6.0.2 on 2026-10-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_attendancerecord_attendancesession_feeaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeinstallment',
            name='due_date',
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='expected_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='payment_plan',
            field=models.CharField(choices=[('EXACT_DATE', 'Exact Date'), ('MONTH', 'Month')], default='EXACT_DATE', max_length=20),
        ),
    ]
